# Generated by Django 5.2.7 on 2026-01-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cored', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(default=None, upload_to='resumes/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
